version: '2'
services:
    api:
        environment: 
            - datastore__connection=${datastore__connection}
            - clientUrls__0=http://hitched-supplier-catalogue.westeurope.cloudapp.azure.com    
        image: hitchedregistry1.azurecr.io/app/suppliercatalogue_api:latest
        ports:
           - "8080:8080"
        links:
            - db
            - ui
        tty: true
    ui:
        environment: 
            - API_DEST=${API_DEST}
            - API_PORT=${API_PORT}    
        image: hitchedregistry1.azurecr.io/app/suppliercatalogue_ui:latest
        ports:
            - "80:80"
        tty:
            true
    db:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - data-volume:/data/db
volumes:
    data-volume:
