version: '2'
services:
    api:
        environment: 
            - datastore__connection=${datastore__connection}
            - clientUrls__0=${clientUrls__0}    
        container_name: suppliercatalogue_api
        build: SupplierCatalogue.API/.
        ports:
           - "8080:8080"
        links:
            - db
            - ui
        tty: true
    ui:
        environment: 
            - API_DEST=${API_DEST}
            - API_PORT=${API_PORT}    
        container_name: suppliercatalogue_ui
        build: SupplierCatalogue.UI/.
        ports:
            - "7080:80"
        tty:
            true
    db:
        container_name: suppliercatalogue_db
        image: mongo:latest
        ports:
            - "27018:27017"
        volumes:
            - data-volume:/data/db
volumes:
    data-volume:
